export const en = {
  format_date: "dd/mm/yyyy",
  format_momnent_date: "DD/MM/YYYY, h:mm:ss a",
  language: "Language",
  date_format: "Date Format",

  home: "Home",
  dashboard: "Dashboard",
  settings: "Settings",
  help: "Help",
  events_history: "Event History",
  menu: "Menu",
  sidebar: "Sidebar",
  dark_mode: "Dark mode",
  light_mode: "Light mode",
  default_mode: "Default mode",
  grey_mode: "Grey mode",
  classic_menu: "Classic menu",
  modern_menu: "Modern menu",

  read: "Read",
  write: "Write",
  delete: "Delete",
  approve: "Approve",
  reject: "Reject",
  confirm: "Confirm",
  create: "Create",
  add: "Add",
  edit: "Edit",
  reset: "Reset",
  search: "Search",
  save: "Save",
  cancel: "Cancel",
  close: "Close",
  select: "Select",
  deselect: "Deselect",
  check_all: "Check All",
  uncheck_all: "Uncheck All",
  yes: "Yes",
  no: "No",

  button_ok: "OK",
  button_yes: "Yes",
  button_no: "No",
  button_home: "Home",
  button_browse: "Browse",
  button_test_connection: "Test Connection",
  button_activate: "Activate",
  button_deactivate: "Deactivate",
  button_filter: "Filter",
  button_more: "More...",
  button_show_more: "Show more...",
  button_view: "View",
  button_view_history: "View History",
  button_update: "Update",
  button_validate: "Validate",
  button_continue: "Continue",
  button_retry: "Retry",
  button_skip: "Skip",
  button_invite: "Invite",
  button_apply: "Apply",
  button_reject: "Reject",
  button_delete: "Delete",
  button_remove: "Remove",
  button_finish: "Finish",
  button_complete: "Complete",
  button_close: "Close",
  button_comment: "Comment",
  button_post: "Post",
  button_upload: "Upload",
  button_download: "Download",
  button_reorder: "Reorder",
  button_confirm: "Confirm",
  button_advance_search: "Advance Search",
  button_basic_search: "Basic Search",
  button_back: "Back",

  msg_confirm_back: "Data has been changed. Your changes will be lost if you do not save them. Are you sure you want to go back?",

  msg_approve_success: "Data have been approved successfully",
  msg_approve_error: "Cannot approve. Internal server error.",
  msg_reject_success: "Data have been rejected successfully",
  msg_reject_error: "Cannot reject. Internal server error.",
  msg_approve_version_error: "Data have been approved or rejected. Please refresh screen and try again.",
  msg_confirm_delete: "Are you sure you want to delete?",
  msg_delete_success: "Data have been deleted successfully",
  msg_delete_fail: "Cannot delete this item. Maybe it was deleted by someone else.",
  msg_role_delete_fail: "Cannot delete this role. Because this role is assigned to some users.",
  msg_delete_confirm_in_list: "Are you sure to delete {0} ?",
  msg_no_change: "You do not change anything.",
  msg_delete_confirm: "Are you sure to delete this item?",
  msg_delete_items_confirm: "Are you sure to delete selected items?",

  msg_no_data_found: "No data found.",
  msg_search_result_sequence: "Items {0} to {1}.",
  msg_search_result_page_sequence: "Items {0} to {1} of {2}. Page {3} of {4}.",
  page_size: "Page Size",
  search_type: "Search Type",
  duration: "Duration",
  order: "Order",
  sort: "Sort",
  sort_relevance: "Relevance",
  sort_date: "Date",
  sort_rating: "Rank",
  sort_by: "Sort by:",

  msg_confirm_save: "Are you sure you want to save?",
  msg_save_success: "Data have been saved successfully",

  error_undefined: "{0} is not allowed to exist.",
  error_exp: "{0} does not match the regular expression.",
  error_type: "Invalid datatype. Type of {0} cannot be {1}.",

  error_boolean: "{0} cannot be boolean.",
  error_strings: "{0} must be an string array.",
  error_numbers: "{0} must be an number array.",
  error_integers: "{0} must be an number array.",
  error_datetimes: "{0} must be an date time array.",
  error_dates: "{0} must be an date array.",

  error_required: "{0} is required.",
  error_minlength: "{0} cannot be less than {1} characters.",
  error_maxlength: "{0} cannot be greater than {1} characters.",

  error_email: "{0} is not a valid email address.",
  error_integer: "{0} is not a valid integer.",
  error_number: "{0} is not a valid number.",
  error_precision: "{0} has a valid precision. Precision must be less than or equal to {1}",
  error_scale: "{0} has a valid scale. Scale must be less than or equal to {1}",
  error_phone: "{0} is not a valid phone number.",
  error_fax: "{0} is not a valid fax number.",
  error_url: "{0} is not a valid URL.",
  error_ipv4: "{0} is not a valid ipv4.",
  error_ipv6: "{0} is not a valid ipv6.",
  error_digit: "{0} must contain digits only.",
  error_dash_digit: "{0} must contain digits and dash only.",
  error_code: "{0} must contain characters and digits only.",
  error_dash_code: "{0} must contain characters and digits and dash only.",
  error_routing_number: "{0} is not a valid routing number.",
  error_check_number: "{0} is not a valid check number.",
  error_post_code: "{0} is not a valid post code.",
  error_ca_post_code: "{0} is not a valid Canada post code.",
  error_us_post_code: "{0} is not a valid US post code.",

  error_min: "{0} must be greater than or equal to {1}.",
  error_max: "{0} must be less than or equal to {1}.",
  error_gt: "{0} must be greater than {1}.",
  error_lt: "{0} must be less than {1}.",
  error_equal: "{0} must be equal to {1}.",
  error_date: "{0} is not a valid date.",
  error_min_date: "{0} cannot be before {1}.",
  error_max_date: "{0} cannot be after {1}.",
  error_from_now: "{0} must be after now.",
  error_from_tomorrow: "{0} must be from tomorrow.",
  error_from: "{0} must be after {1}.",
  error_after_now: "{0} cannot be after now.",
  error_after_tomorrow: "{0} cannot be after tomorrow.",
  error_after: "{0} cannot be after {1}.",

  error_400: "The server will not process the request due to the malformed request syntax.",
  error_401: "You have not logged in or the session was expired. Please log in." /* error_unauthorized */,
  error_403: "You do not have permission for this page or for this action." /* error_forbidden */,
  error_404: "The page is not found." /* error_not_found  */,
  error_409: "Request could not be processed because of conflict in the current state of the resource.",
  error_410: "The resource is no longer available at the server and no forwarding address is known.",

  error_network: "The network is down. Cannot connect to server.",
  error_response_body: "Error while processing the response body.",
  error_submit_failed: "Failed to submit data.",
  error_ajax: "Cannot load page by ajax",

  error_500: "Internal Server error",
  error_502: "Bad Gateway",
  error_503: "Service Unavailable",
  error_504: "Gateway Timeout",

  error_404_title: "404 Not found",
  error_404_message: "Sorry, the page you are looking for could not be found.",
  error_500_title: "500 Internal Server Error",
  error_500_message: "Sorry, the server is wrong. Please try again later.",

  true: "True",
  false: "False",

  status: "Status",
  active: "Active",
  inactive: "Inactive",

  name: "Name",
  display_name: "Display Name",
  gender: "Gender",
  male: "Male",
  female: "Female",  

  please_select: "Please Select",

  address: "Address",
  street: "Street",
  ward: "Ward",
  district: "District",
  city: "City",
  county: "County",
  prefecture: "Prefecture",
  state: "State",
  country: "Country",
  postcode: "Postal Code",

  email: "Email",
  phone: "Telephone",
  notification: "Notification",
  first_name: "First Name",
  last_name: "Last Name",
  middle_name: "Middle Name",
  person_title: "Title",

  from: "From",
  to: "To",
  field: "Field",
  error: "Error",
  info: "Info",
  warning: "Warning",
  success: "Success",

  keyword: "Keyword",
  all: "All",
  pending: "Pending",
  approved: "Approved",
  rejected: "Rejected",
  detail: "Detail",
  description: "Description",
  total: "Total",

  start_date: "Start Date",
  end_date: "End Date",
  start_time: "Start Time",
  end_time: "End Time",

  private_key: "Private Key",
  timestamp: "Timestamp",
}
