export const vi = {
  format_date: "dd/mm/yyyy",
  format_momnent_date: "DD/MM/YYYY, h:mm:ss a",
  language: "Ngôn ngữ",
  date_format: "Định dạng ngày",

  home: "Home",
  dashboard: "Dashboard",
  settings: "Settings",
  help: "Help",
  events_history: "Event History",
  menu: "Menu",
  sidebar: "Sidebar",
  dark_mode: "Dark mode",
  light_mode: "Light mode",
  default_mode: "Default mode",
  grey_mode: "Grey mode",
  classic_menu: "Classic menu",
  modern_menu: "Modern menu",

  read: "Read",
  write: "Write",
  delete: "Delete",
  approve: "Approve",
  reject: "Reject",
  confirm: "Confirm",
  create: "Create",
  add: "Add",
  edit: "Edit",
  reset: "Reset",
  search: "Search",
  save: "Save",
  cancel: "Cancel",
  close: "Close",
  select: "Select",
  deselect: "Deselect",
  check_all: "Check All",
  uncheck_all: "Uncheck All",
  yes: "Yes",
  no: "No",

  button_ok: "OK",
  button_yes: "Yes",
  button_no: "No",
  button_home: "Home",
  button_browse: "Browse",
  button_test_connection: "Test Connection",
  button_activate: "Activate",
  button_deactivate: "Deactivate",
  button_filter: "Filter",
  button_more: "More...",
  button_show_more: "Show more...",
  button_view: "View",
  button_view_history: "View History",
  button_update: "Update",
  button_validate: "Validate",
  button_continue: "Continue",
  button_retry: "Retry",
  button_skip: "Skip",
  button_invite: "Invite",
  button_apply: "Apply",
  button_reject: "Reject",
  button_delete: "Delete",
  button_remove: "Remove",
  button_finish: "Finish",
  button_complete: "Complete",
  button_close: "Close",
  button_comment: "Comment",
  button_post: "Post",
  button_upload: "Upload",
  button_download: "Download",
  button_reorder: "Reorder",
  button_confirm: "Confirm",
  button_advance_search: "Advance Search",
  button_basic_search: "Basic Search",
  button_back: "Back",

  msg_confirm_back: "Data has been changed. Your changes will be lost if you do not save them. Are you sure you want to go back?",
  msg_approve_success: "Data have been approved successfully",
  msg_approve_error: "Cannot approve. Internal server error.",
  msg_reject_success: "Data have been rejected successfully",
  msg_reject_error: "Cannot reject. Internal server error.",
  msg_approve_version_error: "Data have been approved or rejected. Please refresh screen and try again.",
  msg_confirm_delete: "Are you sure you want to delete?",
  msg_delete_success: "Data have been deleted successfully",
  msg_delete_fail: "Cannot delete this item. Maybe it was deleted by someone else.",
  msg_role_delete_fail: "Cannot delete this role. Because this role is assigned to some users.",
  msg_delete_confirm_in_list: "Are you sure to delete {0} ?",
  msg_no_change: "You do not change anything.",
  msg_delete_confirm: "Are you sure to delete this item?",
  msg_delete_items_confirm: "Are you sure to delete selected items?",

  msg_no_data_found: "Không tìm thấy dữ liệu.",
  msg_search_result_sequence: "Hiển thị từ dòng {0} đến {1}.",
  msg_search_result_page_sequence: "Hiển thị từ dòng {0} đến {1} of {2}. Từ trang {3} trên {4} trang.",
  page_size: "Kích thước trang",
  search_type: "Search Type",
  duration: "Duration",
  order: "Order",
  sort: "Sort",
  sort_relevance: "Relevance",
  sort_date: "Date",
  sort_rating: "Rank",
  sort_by: "Sort by:",

  msg_confirm_save: "Bạn có chắc chắn là bạn muốn lưu?",
  msg_save_success: "Lưu dữ liệu thành công.",

  error_undefined: "{0} không được phép tồn tại.",
  error_exp: "{0} không khớp với biểu thức chính quy.",
  error_type: "Kiểu dữ liệu không hợp lệ. Kiểu của {0} không thể là {1}.",

  error_boolean: "{0} cannot be boolean.",
  error_strings: "{0} must be an string array.",
  error_numbers: "{0} must be an number array.",
  error_integers: "{0} must be an number array.",
  error_datetimes: "{0} must be an date time array.",
  error_dates: "{0} must be an date array.",

  error_required: "{0} là bắt buộc.",
  error_minlength: "{0} không được ít hơn {1} ký tự.",
  error_maxlength: "{0} không được nhiều hơn {1} ký tự.",

  error_email: "{0} không phải là địa chỉ email hợp lệ.",
  error_integer: "{0} không phải là số nguyên hợp lệ.",
  error_number: "{0} không phải là số hợp lệ.",
  error_precision: "{0} có độ chính xác không hợp lệ. Độ chính xác phải nhỏ hơn hoặc bằng {1}.",
  error_scale: "{0} có thang đo không hợp lệ. Thang đo phải nhỏ hơn hoặc bằng {1}.",
  error_phone: "{0} không phải là số điện thoại hợp lệ.",
  error_fax: "{0} không phải là số fax hợp lệ.",
  error_url: "{0} không phải là URL hợp lệ.",
  error_ipv4: "{0} không phải là địa chỉ IPv4 hợp lệ.",
  error_ipv6: "{0} không phải là địa chỉ IPv6 hợp lệ.",
  error_digit: "{0} must contain digits only.",
  error_dash_digit: "{0} must contain digits and dash only.",
  error_code: "{0} must contain characters and digits only.",
  error_dash_code: "{0} must contain characters and digits and dash only.",
  error_routing_number: "{0} is not a valid routing number.",
  error_check_number: "{0} is not a valid check number.",
  error_post_code: "{0} is not a valid post code.",
  error_ca_post_code: "{0} is not a valid Canada post code.",
  error_us_post_code: "{0} is not a valid US post code.",

  error_min: "{0} phải lớn hơn hoặc bằng {1}.",
  error_max: "{0} phải nhỏ hơn hoặc bằng {1}.",
  error_gt: "{0} phải lớn hơn {1}.",
  error_lt: "{0} phải nhỏ hơn {1}.",
  error_equal: "{0} phải bằng {1}.",
  error_date: "{0} không phải là ngày hợp lệ.",
  error_min_date: "{0} không được trước {1}.",
  error_max_date: "{0} không được sau {1}.",
  error_from_now: "{0} phải sau thời điểm hiện tại.",
  error_from_tomorrow: "{0} phải từ ngày mai trở đi.",
  error_from: "{0} phải sau {1}.",
  error_after_now: "{0} không được sau thời điểm hiện tại.",
  error_after_tomorrow: "{0} không được sau ngày mai.",
  error_after: "{0} không được sau {1}.",

  error_400: "The server will not process the request due to the malformed request syntax.",
  error_401: "You have not logged in or the session was expired. Please log in." /* error_unauthorized */,
  error_403: "You do not have permission for this page or for this action." /* error_forbidden */,
  error_404: "The page is not found." /* error_not_found  */,
  error_409: "Request could not be processed because of conflict in the current state of the resource.",
  error_410: "The resource is no longer available at the server and no forwarding address is known.",

  error_network: "Mạng đã bị đứt. Không thể kết nối với máy chủ.",
  error_response_body: "Lỗi khi đang xử lí kết quả trả về.",
  error_submit_failed: "Lỗi không gửi dữ liệu lên máy chủ được.",
  error_ajax: "Không thể lấy trang với ajax",

  error_500: "Lỗi trên máy chủ",
  error_502: "Bad Gateway",
  error_503: "Dịch vụ bị gián đoạn",
  error_504: "Gateway Timeout",

  error_404_title: "404 Not found",
  error_404_message: "Xin lỗi, trang bạn đang tìm kiếm không tìm thấy.",
  error_500_title: "500 Internal Server Error",
  error_500_message: "Xin lỗi, máy chủ bị lỗi. Vui lòng thử lại sau.",

  true: "True",
  false: "False",

  status: "Trạng thái",
  active: "Hoạt động",
  inactive: "Không hoạt động",

  name: "Tên",
  display_name: "Tên hiển thị",
  gender: "Giới tính",
  male: "Nam",
  female: "Nữ",

  please_select: "Please Select",

  address: "Address",
  street: "Street",
  ward: "Ward",
  district: "District",
  city: "City",
  county: "Quốc gia",
  prefecture: "Prefecture",
  state: "State",
  country: "Country",
  postcode: "Postal Code",

  email: "Email",
  phone: "Telephone",
  notification: "Notification",
  first_name: "First Name",
  last_name: "Last Name",
  middle_name: "Middle Name",
  person_title: "Title",

  from: "From",
  to: "To",
  field: "Field",
  error: "Error",
  info: "Info",
  warning: "Warning",
  success: "Success",

  keyword: "Keyword",
  all: "All",
  pending: "Pending",
  approved: "Approved",
  rejected: "Rejected",
  detail: "Detail",
  description: "Description",
  total: "Total",

  start_date: "Start Date",
  end_date: "End Date",
  start_time: "Start Time",
  end_time: "End Time",

  private_key: "Private Key",
  timestamp: "Timestamp",
}
