export const vi = {
  format_date: "dd/mm/yyyy",
  format_momnent_date: "DD/MM/YYYY, h:mm:ss a",
  language: "Language",
  date_format: "Date Format",

  home: "Home",
  dashboard: "Dashboard",
  settings: "Settings",
  help: "Help",
  events_history: "Event History",
  menu: "Menu",
  sidebar: "Sidebar",
  dark_mode: "Dark mode",
  light_mode: "Light mode",
  default_mode: "Default mode",
  grey_mode: "Grey mode",
  classic_menu: "Classic menu",
  modern_menu: "Modern menu",
  lang: "Language",

  read: "Read",
  write: "Write",
  delete: "Delete",
  approve: "Approve",
  reject: "Reject",
  confirm: "Confirm",
  create: "Create",
  add: "Add",
  edit: "Edit",
  reset: "Reset",
  search: "Search",
  save: "Save",
  cancel: "Cancel",
  close: "Close",
  select: "Select",
  deselect: "Deselect",
  check_all: "Check All",
  uncheck_all: "Uncheck All",
  yes: "Yes",
  no: "No",

  button_ok: "OK",
  button_yes: "Yes",
  button_no: "No",
  button_home: "Home",
  button_browse: "Browse",
  button_test_connection: "Test Connection",
  button_activate: "Activate",
  button_deactivate: "Deactivate",
  button_filter: "Filter",
  button_more: "More...",
  button_show_more: "Show more...",
  button_view: "View",
  button_view_history: "View History",
  button_update: "Update",
  button_validate: "Validate",
  button_continue: "Continue",
  button_retry: "Retry",
  button_skip: "Skip",
  button_invite: "Invite",
  button_apply: "Apply",
  button_reject: "Reject",
  button_delete: "Delete",
  button_remove: "Remove",
  button_finish: "Finish",
  button_complete: "Complete",
  button_close: "Close",
  button_comment: "Comment",
  button_post: "Post",
  button_upload: "Upload",
  button_download: "Download",
  button_reorder: "Reorder",
  button_confirm: "Confirm",
  button_advance_search: "Advance Search",
  button_basic_search: "Basic Search",
  button_back: "Back",

  msg_confirm_back: "Data has been changed. Your changes will be lost if you do not save them. Are you sure you want to go back?",
  msg_confirm_save: "Are you sure you want to save?",
  msg_save_success: "Data have been saved successfully",
  msg_confirm_submit: "Are you sure you want to submit?",
  msg_submit_success: "Data have been submitted successfully",
  msg_confirm_approve: "Are you sure you want to approve?",
  msg_approve_success: "Data have been approved successfully",
  msg_approve_conflict: "Cannot approve. Maybe someone already approved or rejected.",
  msg_approver_conflict: "Approver cannot be submitter.",
  msg_approve_error: "Cannot approve. Internal server error.",
  msg_confirm_reject: "Are you sure you want to reject?",
  msg_reject_success: "Data have been rejected successfully",
  msg_rejected_conflict: "Cannot reject. Maybe someone already approved or rejected.",
  msg_reject_error: "Cannot reject. Internal server error.",
  // msg_approve_version_error: "Data have been approved or rejected. Please refresh screen and try again.",
  msg_confirm_delete: "Are you sure you want to delete?",
  msg_delete_confirm_in_list: "Are you sure to delete {0} ?",
  msg_delete_failed: "This item was not deleted successfully",
  msg_no_change: "You do not change anything.",
  msg_delete_confirm: "Are you sure to delete this item?",
  msg_delete_items_confirm: "Are you sure to delete selected items?",

  msg_no_data_found: "No data found.",
  msg_search_result_sequence: "Items {0} to {1}.",
  msg_search_result_page_sequence: "Items {0} to {1} of {2}. Page {3} of {4}.",
  page_size: "Page Size",
  search_type: "Search Type",
  duration: "Duration",
  order: "Order",
  sort: "Sort",
  sort_relevance: "Relevance",
  sort_date: "Date",
  sort_rating: "Rank",

  error_not_found: "Not found.",
  error_internal: "System Error.",
  error_system_error: "System Error.",
  error_required: "{0} is required.",
  error_invalid: "You have inserted invalid {0}. Please try again",
  error_required_minlength: "{0} is required and {0} cannot be less than {1} characters.",
  error_minlength: "{0} cannot be less than {1} characters.",
  error_maxlength: "{0} cannot be greater than {1} characters.",
  error_min: "{0} must be greater than or equal to {1}.",
  error_max: "{0} must be smaller than or equal to {1}.",
  error_equal: "{0} must be equal to {1}.",
  error_greater: "{0} must be greater than {1}.",
  error_min_date: "{0} cannot be before {1}.",
  error_max_date: "{0} cannot be after {1}.",
  error_range: "{0} is not in the range {1} through {2}.",
  error_byte: "{0} must be a byte.",
  error_short: "{0} must be a short.",
  error_long: "{0} must be a long.",
  error_float: "{0} must be a float.",
  error_double: "{0} must be a double.",
  error_integer: "{0} must be a integer.",
  error_number: "{0} must be a number.",
  error_required_number: "{0} is required and must be a number",
  error_date: "{0} is not a valid date.",
  error_email: "Please enter a valid email address.",
  error_required_email: "{0} is required and must be a valid email address.",
  error_phone: "Invalid phone number. Please include area code and full phone number.",
  error_fax: "Invalid fax number. Please include area code and full fax number.",
  error_url: "{0} is not a valid URL.",
  error_post_code: "{0} is not a valid postal code.",
  error_us_post_code: "{0} is not a valid US postal code.",
  error_ca_post_code: "{0} is not a valid Canada postal code.",
  error_cash: "Please enter a valid amount money.",
  error_credit_card: "{0} is a valid credit card",
  error_port: "Invalid Port (min. 0, max. 65535)",
  error_password:
    "Your new password is invalid. The password length must be between 8 and 14 characters, and no dictionary words permitted. Also, your password must contain at least 3 out of 4 following rules: lowercase, uppercase, numerals, special characters such as !@#$%^&*(){}[].",
  error_account_number: "{0} is not a valid checking account number.",
  error_check_number: "{0} is not a valid check number.",
  error_routing_number: "{0} is not a valid routing number.",
  error_digit: "{0} must contain digit only.",
  error_dash_digit: "{0} must contain dash or digit only.",
  error_code: "{0} is not a valid code.",
  error_dash_code: "{0} must contain character or digit or dash.",
  error_ipv4: "{0} is not a valid ipv4.",
  error_ipv6: "{0} is not a valid ipv6.",

  error_item_exist: "This {0} is already existed in the system. Please try a different one",
  error_item_not_exist: "This {0} does not exist in the system. Please try a different one",

  error_network: "Cannot access server. Maybe network is corrupted.",
  error_500: "Internal Server error",
  error_502: "Bad Gateway",
  error_503: "Service Unavailable",
  error_504: "Gateway Timeout",

  error_404_title: "404 Not found",
  error_404_message: "Sorry, the page you are looking for could not be found.",
  error_500_title: "500 Internal Server Error",
  error_500_message: "Sorry, the server is wrong. Please try again later.",

  error_400: "Bad request",
  error_401: "You have not logged in or the session was expired. Please log in." /* error_unauthorized */,
  error_404: "Item was not found." /* error_not_found  */,
  error_403: "You do not have permission for this page or for this action." /* error_forbidden */,

  error_version: "Data has been changed by someone. Please refresh screen and continue.",
  error_conflict: "Data has been changed by someone. Please refresh screen and continue.",
  error_data_corrupt: "Data has been corrupt. You cannot proceed this business.",
  error_required_id: "You must input id.",
  error_duplicate_key: "The id is duplicated.",
  error_duplicated: "{0} is duplicated.",

  error_permission: "Permission error",
  error_permission_search: "You do not permission to use this page.",
  error_permission_view: "You do not permission to use this page.",
  error_permission_add: 'You do not have "add" permission. You are not allowed to "add".',
  error_permission_edit: 'You do not have "add" permission. You are not allowed to "edit".',
  error_permission_delete: 'You do not have "add" permission. You are not allowed to "delete".',

  true: "True",
  false: "False",

  status: "Status",
  active: "Active",
  inactive: "Inactive",

  status_draft: "Draft",
  status_submitted: "Submitted",
  status_rejected: "Rejected",
  status_approved: "Approved",
  status_published: "Published",
  status_expired: "Expired",

  please_select: "Please Select",

  address: "Address",
  street: "Street",
  ward: "Ward",
  district: "District",
  city: "City",
  county: "County",
  prefecture: "Prefecture",
  state: "State",
  country: "Country",
  postcode: "Postal Code",

  gender: "Gender",
  male: "Male",
  female: "Female",
  name: "Name",

  fullname: "Full Name",
  email: "Email",
  phone: "Telephone",
  notification: "Notification",
  first_name: "First Name",
  last_name: "Last Name",
  middle_name: "Middle Name",
  display_name: "Display Name",
  person_title: "Title",

  from: "From",
  to: "To",
  field: "Field",
  error: "Error",
  info: "Info",
  warning: "Warning",
  success: "Success",

  keyword: "Keyword",
  remark: "Remark",
  all: "All",
  pending: "Pending",
  approved: "Approved",
  rejected: "Rejected",
  detail: "Detail",
  description: "Description",
  number: "No.",
  total: "Total",

  start_date: "Start Date",
  end_date: "End Date",
  start_time: "Start Time",
  end_time: "End Time",

  private_key: "Private Key",
  action: "Action",
  resource: "Resource",
  timestamp: "Timestamp",
  ip: "IP",

  categories: "Categories",
  category: "Category",
  path: "Path",
  icon: "Icon",
  type: "Type",
  parent: "Parent",
  sequence: "Sequence",

  contact: "Contact",
  articles: "Articles",
  article: "Article",
  jobs: "Jobs",
  job: "Job",
  id: "Id",
  title: "Title",
  contents: "Contents",
  content: "Content",
  body: "Body",
  thumbnail: "Thumbnail",
  published_at: "Published At",
  published_at_from: "Published At From",
  published_at_to: "Published At To",
  company: "Company",
  job_title: "Job Title",
  requirements: "Requirements",
  location: "Location",
  position: "Position",
  quantity: "Quantity",
  min_salary: "Min Salary",
  max_salary: "Max Salary",

  created_by: "Created By",
  created_at: "Created At",
  submitted_by: "Submitted By",
  approved_by: "Approved By",

  contacts: "Contacts",
  submitted_at: "Submitted At",
  contacted_by: "Contacted By",
  contacted_at: "Contacted At",
  message: "Message",
}
